CREATE TABLE "PRODUCT" 
(
  PRODUCT_id VARCHAR2(20) PRIMARY KEY,
  PRODUCT_name VARCHAR2(20) NOT NULL,
  price NUMBER,
  Categorie VARCHAR2(20)
);

CREATE TABLE "ORDER" 
(
  Custumer_id VARCHAR2(20),
  PRODUCT_id VARCHAR2(20),
  Quantity NUMBER,
  Total_amount NUMBER,
  OrderDates DATE DEFAULT SYSDATE
);

CREATE TABLE "CUSTUMERS"
(
  CUSTUMERS_id VARCHAR2(20) PRIMARY KEY,
  CUSTUMERS_name VARCHAR2(20) NOT NULL,
  CUSTUMERS_tel NUMBER
);
